import Head from 'next/head'

import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';
export default function Home() {
  const [dark,setDark] = useState(false);

  return (
    <div className={dark ? "dark" :""} >
      <Head>
        <title>Ammar Hussain-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-20 dark:bg-gray-900' >
       

       <section className='  min-h-screen '>
       <nav className=' flex justify-between mb-12 py-10'>
       <h1 className='text-xl font-burtons dark:text-white'>developed by Ammar</h1>
       <ul className='flex items-center'>
       <li><BsFillMoonStarsFill onClick={()=>setDark(!dark)} className='cursor-pointer text-2xl dark:text-white '/></li>
       <li > <a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:bg-white'>Resume</a></li>
       </ul>
       </nav> 
       <div className='p-10 text-center '>
       <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Ammar Hussain</h2>
       <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer.</h3>
       <p className='py-5 text-md leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Freelance Providing Services for Programing and design Content
       needs. Join me Down  below and lets get cracking!
       </p>
       </div>
       <div className='flex justify-center text-5xl gap-16 py-3 text-gray-600'>
      <a href='https://twitter.com/AmmarHu39447499' target= "blank"> <AiFillTwitterCircle className='dark:text-white' /></a>
      <a href='https://www.linkedin.com/in/ammar-hussain-2a0025184/' target= "blank"> <AiFillLinkedin className='dark:text-white'/></a> 
        <AiFillYoutube className='dark:text-white'/>
       </div>
       <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mx-auto mt-20 overflow-hidden md:h-96 md:w-96'>
      <Image src={deved} alt="Images"  layout='fill' objectFit='cover'/>
       </div>
      </section>
      <section>
      <div>
      <h3 className='text-3xl py-1 dark:text-white' >Services I offer </h3>
     <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Since the begining of my journey  as a freelance 🤘 
     and developer, I have done remote work for
     <span className ='text-teal-500'> agencies </span>
     <span className ='text-teal-500'>consulted for startups </span>
     and collaborated with talented people to create digital products for both business and consumer use. I am quietly confident, naturally curious, and perpetually working on improving my chops one design problem at a time
     </p>
     <p className='text-md py-2 leading-8 text-gray-800 dark:text-white '>
     I offer from a wide range of services including
      <span className ='text-teal-500'> Web Design </span>
      <span className ='text-teal-500'>Web Development </span>
     and also a teacher for <span className ='text-teal-500'>Programming</span>
     

     </p>
      </div>
      <div  className='lg:flex gap-10'>
      <div  className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white '>
      <Image src={design} width={100} height={100} alt="design" className='mx-auto' />
      <h3 className='text-lg pt-8 font-medium pb-2'>Beautiful designs</h3>
      <p className='py-2'>Creating elegent  designs suited
        for your needs following coure design theory 
        </p>
        <h4 className='py-4 text-teal-600'>Design tools I use</h4>
        <p className='text-gray-800 py-1'>Photoshop</p>
        <p className='text-gray-800 py-1'>Illustrator</p>
        <p className='text-gray-800 py-1'>XD</p>
        <p className='text-gray-800 py-1'>Sketch</p>
        <p className='text-gray-800 py-1'>Figma</p>
      </div>



      <div  className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white  '>
      <Image src={consulting} width={100} height={100} alt="design" className='mx-auto' />
      <h3 className='text-lg pt-8 font-medium pb-2'>Beautiful designs</h3>
      <p className='py-2'>Creating elegent  designs suited
        for your needs following coure design theory 
        </p>
        <h4 className='py-4 text-teal-600'>Design tools I use</h4>
        <p className='text-gray-800 py-1'>Photoshop</p>
        <p className='text-gray-800 py-1'>Illustrator</p>
        <p className='text-gray-800 py-1'>XD</p>
        <p className='text-gray-800 py-1'>Sketch</p>
        <p className='text-gray-800 py-1'>Figma</p>
      </div>



      <div  className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white '>
      <Image src={code} width={100} height={100} alt="design" className='mx-auto' />
      <h3 className='text-lg pt-8 font-medium pb-2'>Beautiful designs</h3>
      <p className='py-2'>Creating elegent  designs suited
        for your needs following coure design theory 
        </p>
        <h4 className='py-4 text-teal-600'>Design tools I use</h4>
        <p className='text-gray-800 py-1'>Photoshop</p>
        <p className='text-gray-800 py-1'>Illustrator</p>
        <p className='text-gray-800 py-1'>XD</p>
        <p className='text-gray-800 py-1'>Sketch</p>
        <p className='text-gray-800 py-1'>Figma</p>
      </div>
      </div>
      </section>
      <section>
     <div>
     <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
     <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Since the begining of my journey  as a freelance 🤘 
     and developer, I have done remote work for
     <span className ='text-teal-500'> agencies </span>
     <span className ='text-teal-500'>consulted for startups </span>
     and collaborated with talented people to create digital products for both business and consumer use. I am quietly confident, naturally curious, and perpetually working on improving my chops one design problem at a time
     </p>
     </div>


     <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
     <div className='flex-1 basis-1/3'>
     <Image src={web1} alt="web1" className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
     </div>
     <div className='flex-1 basis-1/3'>
     <Image src={web2} alt="web2" className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
     </div>
     <div className='flex-1 basis-1/3'>
     <Image src={web3} alt="web3" className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
     </div>
     <div className='flex-1 basis-1/3'>
     <Image src={web4} alt="web4" className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
     </div>
     <div className='flex-1 basis-1/3'>
     <Image src={web5} alt="web5" className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
     </div>
     <div className='flex-1 basis-1/3'>
     <Image src={web6} alt="web6" className='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
     </div>
     </div>
      </section>
      </main>

    </div>
  )
}
